version: '3.8'
services:

  postgres:
    image: postgres:13.7-alpine
    container_name: shareit_db_postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  server:
    build: server
    container_name: shareit_server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  gateway:
    build: gateway
    container_name: shareit_gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090